# Generated by Django 2.2.7 on 2020-01-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='image3',
        ),
    ]
