# Generated by Django 2.2.7 on 2019-12-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='user',
            new_name='created_by',
        ),
    ]
