# Generated by Django 2.2.7 on 2020-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='in_archive',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Об'єктів в архіві"),
        ),
        migrations.AddField(
            model_name='realtor',
            name='limit_offers',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Ліміт оголошень, штук'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='offers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Об'єктів на продаж"),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(help_text='міжнародний формат, +38067XXXYYZZ', max_length=13, unique=True, verbose_name='Телефон основний'),
        ),
    ]
