# Generated by Django 2.2.7 on 2020-01-05 11:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtor', '0002_auto_20200103_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(extent=(31.44, 49.217, 32.47, 49.68), help_text='<em>Просто поставте маркер на карту</em>', srid=4326, verbose_name='Місце на мапі')),
                ('name', models.CharField(max_length=255, verbose_name='Назва агенції')),
                ('phone1', models.CharField(help_text='міжнародний формат, +38067XXXYYZZ', max_length=13, verbose_name='Телефон основний')),
                ('phone2', models.CharField(help_text='міжнародний формат, +38067XXXYYZZ', max_length=13, verbose_name='Телефон додатковий')),
                ('body', models.TextField(help_text='<em>До 2000 символів</em>', max_length=2000, verbose_name='Про агенство')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('num_visits', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Логотип')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencys', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
