# Generated by Django 2.2.7 on 2020-01-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='address',
        ),
        migrations.AlterField(
            model_name='realtor',
            name='agensy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtors', to='realtor.Agency', verbose_name='Агенство'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='bio',
            field=models.TextField(blank=True, help_text='<em>все, що вважаєте за потрібне про себе, свою фірму до 1000 знаків</em>', max_length=1000, null=True, verbose_name='Подробиці про ріелтора'),
        ),
    ]
