# Generated by Django 2.2.7 on 2020-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_auto_20200227_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('offer_type', models.CharField(max_length=50)),
                ('offer_id', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
