# Generated by Django 2.2.7 on 2020-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_leadgenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(blank=True, help_text='міжнародний формат, +38067XXXYYZZ', max_length=13, null=True, unique=True, verbose_name='Телефон основний'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='start_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Рік початку роботи ріелтором'),
        ),
    ]
