# Generated by Django 2.2.7 on 2020-03-24 14:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_auto_20200307_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(extent=(31.0, 49.0, 33.0, 50.0), help_text='<em>Просто поставте маркер на карту</em>', srid=4326, verbose_name='Місце на мапі'),
        ),
    ]
