# Generated by Django 2.2.7 on 2020-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bbarbecue',
            field=models.BooleanField(default=False, verbose_name='Бесідка, мангал, барбекю'),
        ),
        migrations.AddField(
            model_name='house',
            name='cleaner',
            field=models.BooleanField(default=False, verbose_name='Центральний пилосос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='balcony',
            field=models.BooleanField(verbose_name='Балкон'),
        ),
    ]
