# Generated by Django 2.2.7 on 2019-12-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='House',
        ),
    ]
