# Generated by Django 2.2.7 on 2020-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='architecture',
            field=models.CharField(choices=[('ампір', 'ампір'), ('класицизм', 'класицизм'), ('chalet', 'шале'), ('конструктивізм', 'конструктивізм'), ('хай-тек', 'хай-тек'), ('ренесанс', 'ренесанс'), ('барокко', 'барокко'), ('модерн', 'модерн'), ('інший', 'інший')], default='classicism', max_length=50, verbose_name='Архітектурний стиль'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_estate',
            field=models.DecimalField(decimal_places=2, help_text='наприклад, 0.06', max_digits=6, verbose_name='Загальна площа земельної ділянки, га'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathroom',
            field=models.CharField(choices=[('Роздільний', 'Роздільний'), ('Суміжний', 'Суміжний'), ('2 і більше', '2 і більше'), ('Санвузол відсутній', 'Санвузол відсутній')], max_length=50, verbose_name='Санвузол'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating',
            field=models.CharField(choices=[('Централізоване', 'Централізоване'), ('Власна котельня', 'Власна котельня'), ('Індивідуальне газове', 'Індивідуальне газове'), ('Індивідуальне електричне', 'Індивідуальне електричне'), ('Твердопаливне', 'Твердопаливне'), ('Тепловий насос', 'Тепловий насос'), ('Комбіноване', 'Комбіноване'), ('Інше', 'Інше')], max_length=50, verbose_name='Опалення'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(help_text='70 знаків', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_object',
            field=models.CharField(choices=[('будинок', 'будинок'), ('частина будинку', 'частина будинку')], default='flat', max_length=50, verbose_name="Тип об'єкта"),
        ),
        migrations.AlterField(
            model_name='house',
            name='type_offer',
            field=models.CharField(choices=[('продажа', 'Продаж'), ('оренда', 'Оренда довгострокова')], default='sale', max_length=50, verbose_name='Тип оголошення'),
        ),
        migrations.AlterField(
            model_name='house',
            name='walls',
            field=models.CharField(choices=[('цегла силікатна', 'цегла силікатна'), ('цегла червона', 'цегла червона'), ('керамоблок', 'керамоблок'), ('деревяний брус', 'деревяний брус'), ('шлакоблок', 'шлакоблок'), ('піноблок', 'піноблок'), ('газоблок', 'газоблок'), ('СІП панель', 'СІП панель'), ('other', 'Інше')], max_length=50, verbose_name='Матеріал стін'),
        ),
    ]
