# Generated by Django 2.2.7 on 2020-01-05 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20191230_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(extent=(31.44, 49.217, 32.47, 49.68), help_text='<em>Просто поставте маркер на карту</em>', srid=4326, verbose_name='Місце на мапі'),
        ),
    ]
