# Generated by Django 2.2.7 on 2020-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20200117_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type_offer',
            field=models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда довгострокова')], default='SALE', max_length=50, verbose_name='Тип оголошення'),
        ),
    ]
