# Generated by Django 2.2.7 on 2020-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='archivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Оголошення в архіві'),
        ),
    ]
