# Generated by Django 2.2.7 on 2020-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20200117_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Heating',
            field=models.CharField(choices=[('centralize', 'Централізоване'), ('own_boiler_room', 'Власна котельня'), ('individual_gas', 'Індивідуальне газове'), ('individual_electricity', 'Індивідуальне електричне'), ('hard_fuel', 'Твердопаливне'), ('heat_pump', 'Тепловий насос'), ('combination', 'Комбіноване'), ('other', 'Інше')], default='other', max_length=25, verbose_name='Опалення'),
        ),
    ]
