# Generated by Django 2.2.7 on 2020-02-01 15:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import land.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offer', models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда довгострокова')], default='SALE', max_length=50, verbose_name='Тип оголошення')),
                ('title', models.CharField(help_text='до 70 знаків', max_length=70, verbose_name='Заголовок оголошення')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(extent=(31.44, 49.217, 32.47, 49.68), help_text='<em>обведіть багатокутник по формі земельної ділянки</em>', srid=4326, verbose_name='Площа на мапі')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('currency', models.CharField(choices=[('UAH', 'грн.'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='Валюта')),
                ('agree_price', models.BooleanField(verbose_name='Договірна')),
                ('no_commission', models.BooleanField(verbose_name='Без комісії')),
                ('exchange', models.BooleanField(verbose_name='Можливість обміну')),
                ('collaboration', models.BooleanField(verbose_name='Готовий співпрацювати з ріелторами')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 1')),
                ('MSZoning', models.CharField(choices=[('A', 'СІЛЬСЬКЕ ГОСПОДАРСТВО'), ('C', 'КОМЕРЦІЙНА'), ('FV', 'ПРИМІСЬКА'), ('I', 'ПРОМИСЛОВА'), ('RH', 'ВИСОКА ЩІЛЬНІСТЬ ЗАБУДОВИ'), ('RL', 'НИЗЬКА ЩІЛЬНІСТЬ ЗАБУДОВИ'), ('RP', 'КОТЕДЖНЕ МІСТЕЧКО З НИЗЬКОЮ ЩІЛЬНІСТЮ ЗАБУДОВИ'), ('RM', 'СЕРЕДНЯ ЩІЛЬНІСТЬ ЗАБУДОВИ')], default='A', help_text='Визначає загальну класифікацію зонування продажу', max_length=3, verbose_name='Зонування')),
                ('LandArea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Загальна площа земельної ділянки, га')),
                ('LotShape', models.CharField(choices=[('Reg', 'Правильна форма'), ('IR1', 'Майже правильна'), ('IR2', 'Помірно неправильна'), ('IR3', 'Дуже неправильна')], default='Reg', max_length=3, verbose_name='Форма земельної ділянки')),
                ('LandContour', models.CharField(choices=[('Lvl', 'Все в одному рівні, плоска ділянка'), ('Bnk', 'Швидкий і значний підйом з вулиці в будівлю'), ('HLS', 'Значний нахил ділянки з боку в бік'), ('Low', 'Нижче рівня вулиці, улоговина'), ('Slp', 'Помірний рівномірний схил')], default='Lvl', max_length=3, verbose_name='Плоскість власності')),
                ('Fence', models.CharField(choices=[('GdPrv', 'Добре захищена приватність'), ('MnPrv', 'Мінімальна приватність'), ('BadPrv', 'Погано захищена приватність'), ('NA', 'Немає огорожі')], default='NA', max_length=6, verbose_name='Якість паркану, огорожі')),
                ('body', models.TextField(help_text='<em>до 4000 знаків</em>', max_length=4000, verbose_name='Опис')),
                ('gas', models.BooleanField(verbose_name='Газ')),
                ('central_water_supply', models.BooleanField(verbose_name='Центральний водопровід')),
                ('well', models.BooleanField(verbose_name='Скважина')),
                ('electricity', models.BooleanField(verbose_name='Електрика')),
                ('central_sewerage', models.BooleanField(verbose_name='Центральна каналізація')),
                ('septic_tank', models.BooleanField(verbose_name='Каналізація септик')),
                ('removal_of_waste', models.BooleanField(verbose_name='Вивіз відходів')),
                ('asphalt_road', models.BooleanField(verbose_name='Асфальтована дорога')),
                ('river', models.BooleanField(verbose_name='Річка')),
                ('reservoir', models.BooleanField(verbose_name='Водосховище')),
                ('lake', models.BooleanField(verbose_name='Озеро')),
                ('hills', models.BooleanField(verbose_name='Пагорби')),
                ('mountains', models.BooleanField(verbose_name='Гори')),
                ('park', models.BooleanField(verbose_name='Парк')),
                ('forest', models.BooleanField(verbose_name='Ліс')),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('num_visits', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to=settings.AUTH_USER_MODEL, verbose_name='Власник оголошення')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
