# Generated by Django 2.2.7 on 2020-03-01 14:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20200226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='archivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Оголошення в архіві'),
        ),
        migrations.AlterField(
            model_name='land',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(extent=(31.44, 49.217, 32.47, 49.68), help_text='<em>багатокутник по формі земельної ділянки</em>', srid=4326, verbose_name='Площа на мапі'),
        ),
    ]
