# Generated by Django 2.2.7 on 2020-03-07 18:55

from django.db import migrations, models
import land.models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_auto_20200301_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 2'),
        ),
        migrations.AddField(
            model_name='land',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 3'),
        ),
        migrations.AddField(
            model_name='land',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 4'),
        ),
        migrations.AddField(
            model_name='land',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 5'),
        ),
        migrations.AddField(
            model_name='land',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 6'),
        ),
        migrations.AddField(
            model_name='land',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 7'),
        ),
        migrations.AddField(
            model_name='land',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 8'),
        ),
        migrations.AddField(
            model_name='land',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=land.models.Land.user_directory_path, verbose_name='Світлина 9'),
        ),
    ]
