# Generated by Django 2.2.7 on 2020-03-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_land_cadastral_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='asphalt_road',
        ),
        migrations.RemoveField(
            model_name='land',
            name='central_sewerage',
        ),
        migrations.RemoveField(
            model_name='land',
            name='central_water_supply',
        ),
        migrations.RemoveField(
            model_name='land',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='land',
            name='forest',
        ),
        migrations.RemoveField(
            model_name='land',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='land',
            name='hills',
        ),
        migrations.RemoveField(
            model_name='land',
            name='lake',
        ),
        migrations.RemoveField(
            model_name='land',
            name='mountains',
        ),
        migrations.RemoveField(
            model_name='land',
            name='park',
        ),
        migrations.RemoveField(
            model_name='land',
            name='removal_of_waste',
        ),
        migrations.RemoveField(
            model_name='land',
            name='reservoir',
        ),
        migrations.RemoveField(
            model_name='land',
            name='river',
        ),
        migrations.RemoveField(
            model_name='land',
            name='septic_tank',
        ),
        migrations.RemoveField(
            model_name='land',
            name='well',
        ),
    ]
