# Generated by Django 2.2.7 on 2020-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_auto_20200325_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='MSZoning',
            field=models.CharField(choices=[('A', 'Присадибна ділянка для будівництва приватного будинку'), ('C', 'Особисте селянське господарство'), ('FV', 'Садова або дачне будівництво'), ('I', 'Комерційна діяльність'), ('RH', 'Під багатоквартирний будинок'), ('RL', 'Під котеджне містечко'), ('RP', 'Для ведення товарного сільського господарства'), ('RM', 'Приватний будинок + особисте селянське господарство')], default='A', max_length=3, verbose_name='Тип земельної ділянки'),
        ),
    ]
