# Generated by Django 2.2.7 on 2019-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerflat',
            name='building',
            field=models.CharField(choices=[('royal', 'Царський будинок'), ('stalin', 'Сталінка'), ('hruschov', 'Хрущовка'), ('czech', 'Чешка'), ('guest', 'Гостинка'), ('sovmin', 'Совмін'), ('hostel', 'Гуртожиток'), ('90', 'Житловий фонд 80-90'), ('2000', 'Житловий фонд 91-2000'), ('2010', 'Житловий фонд 2001-2010'), ('2019', 'Житловий фонд від 2011'), ('constraction', 'На етапі будівництва')], max_length=12, verbose_name='Тип будинку'),
        ),
    ]
