# Generated by Django 2.2.7 on 2019-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='body',
            field=models.TextField(help_text='<em>до 2000 знаків</em>', max_length=2000, verbose_name='Опис'),
        ),
    ]
