# Generated by Django 2.2.7 on 2020-01-12 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Райони', (('700-richchia', '700-річчя'), ('Vantazhnyi port', 'Вантажний порт'), ('Vodokanal-Nevskoho', 'Водоканал-Невського'), ('Dakhnivka', 'Дахнівка'), ('Dniprovskyi', 'Дніпровський'), ('Zaliznychnyi vokzal', 'Залізничний вокзал'), ('Zelena', 'Зелена'), ('k-t Myr', 'к-т Мир'), ('Kazbet', 'Казбет'), ('Litak', 'Літак'), ('Lunacharskyi', 'Луначарський'), ('Mytnytsia', 'Митниця'), ('Mytnytsia-richport', 'Митниця-річпорт'), ('Mytnytsia-tsentr', 'Митниця-центр'), ('PZR', 'ПЗР'), ('Prydniprovskyi', 'Придніпровський'), ('Piatykhatky', 'Пятихатки'), ('Raion D', 'Район Д'), ('Siedova', 'Сєдова'), ('Sosnivka', 'Соснівка'), ('Sosnivskyi', 'Соснівський'), ('Khimselyshche', 'Хімселище'), ('Tsentr', 'Центр'), ('Shkilna', 'Шкільна'), ('Yabluchnyi', 'Яблучний'))), ('Передмістя', (('Biloziria', "Білозір'я"), ('Heronymivka', 'Геронимівка'), ('Orshanets', 'Оршанець'), ('Ruska Poliana', 'Руська Поляна'), ('Chervona Sloboda', 'Червона Слобода'))), ('Села', (('Yelyzavetovka', 'Єлизаветовка'), ('Irdyn', 'Ірдинь'), ('Baibuzy', 'Байбузи'), ('Berezniaky', 'Березняки'), ('Budyshche', 'Будище'), ('Buzukiv', 'Бузуків'), ('Verhuny', 'Вергуни'), ('Dubiivka', 'Дубіївка'), ('Dumantsi', 'Думанці'), ('Kumeiky', 'Кумейки'), ('Lesky', 'Леськи'), ('Lozivok', 'Лозівок'), ('Moshny', 'Мошни'), ('Moshnohiria', "Мошногір'я"), ('Nechaivka', 'Нечаївка'), ('Novoselivka', 'Новоселівка'), ('Pervomaiske', 'Первомайське'), ('Sahunivka', 'Сагунівка'), ('Svitanok', 'Світанок'), ('Svydivok', 'Свидівок'), ('Sokyrno', 'Сокирно'), ('Sofiivka', 'Софіївка'), ('Stepanky', 'Степанки'), ('Tubiltsi', 'Тубільці'), ('Khatsky', 'Хацьки'), ('Khreshchatyk', 'Хрещатик'), ('Khudiaky', 'Худяки'), ('Khutory', 'Хутори'), ('Chorniavka', 'Чорнявка'), ('Shelepukhy', 'Шелепухи'), ('Yasnoziria', "Яснозір'я")))], max_length=255, verbose_name='Назва, Район, зона, територія')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(extent=(31.44, 49.217, 32.47, 49.68), help_text='окресліть фігуру на мапі, що відповідає потрібній площині', srid=4326, verbose_name='Площа на мапі')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
