# Generated by Django 2.2.7 on 2020-01-02 14:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20191230_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='house',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='street',
        ),
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(default='some address', max_length=255, verbose_name='Адреса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(extent=(31.44, 49.217, 32.47, 49.68), srid=4326),
        ),
    ]
