# Generated by Django 2.2.7 on 2020-01-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(choices=[('Райони', (('700-richchia', '700-річчя'), ('Vantazhnyi port', 'Вантажний порт'), ('Vodokanal', 'Водоканал'), ('Dakhnivka', 'Дахнівка'), ('Dniprovskyi', 'Дніпровський'), ('Zaliznychnyi vokzal', 'Залізничний вокзал'), ('Zelena', 'Зелена'), ('k-t Myr', 'к-т Мир'), ('Kazbet', 'Казбет'), ('Litak', 'Літак'), ('Lunacharskyi', 'Луначарський'), ('Mytnytsia', 'Митниця'), ('Mytnytsia-richport', 'Митниця-річпорт'), ('Mytnytsia-tsentr', 'Митниця-центр'), ('PZR', 'ПЗР'), ('Prydniprovskyi', 'Придніпровський'), ('Piatykhatky', 'Пятихатки'), ('Raion D', 'Район Д'), ('Siedova', 'Сєдова'), ('Sosnivka', 'Соснівка'), ('Sosnivskyi', 'Соснівський'), ('Khimselyshche', 'Хімселище'), ('Tsentr', 'Центр'), ('Shkilna', 'Шкільна'), ('Yabluchnyi', 'Яблучний'))), ('Передмістя', (('Biloziria', "Білозір'я"), ('Heronymivka', 'Геронимівка'), ('Orshanets', 'Оршанець'), ('Ruska Poliana', 'Руська Поляна'), ('Chervona Sloboda', 'Червона Слобода'))), ('Села', (('Yelyzavetovka', 'Єлизаветовка'), ('Irdyn', 'Ірдинь'), ('Baibuzy', 'Байбузи'), ('Berezniaky', 'Березняки'), ('Budyshche', 'Будище'), ('Buzukiv', 'Бузуків'), ('Verhuny', 'Вергуни'), ('Dubiivka', 'Дубіївка'), ('Dumantsi', 'Думанці'), ('Kumeiky', 'Кумейки'), ('Lesky', 'Леськи'), ('Lozivok', 'Лозівок'), ('Moshny', 'Мошни'), ('Moshnohiria', "Мошногір'я"), ('Nechaivka', 'Нечаївка'), ('Novoselivka', 'Новоселівка'), ('Pervomaiske', 'Первомайське'), ('Sahunivka', 'Сагунівка'), ('Svitanok', 'Світанок'), ('Svydivok', 'Свидівок'), ('Sokyrno', 'Сокирно'), ('Sofiivka', 'Софіївка'), ('Stepanky', 'Степанки'), ('Tubiltsi', 'Тубільці'), ('Khatsky', 'Хацьки'), ('Khreshchatyk', 'Хрещатик'), ('Khudiaky', 'Худяки'), ('Khutory', 'Хутори'), ('Chorniavka', 'Чорнявка'), ('Shelepukhy', 'Шелепухи'), ('Yasnoziria', "Яснозір'я")))], max_length=255, verbose_name='Назва, Район, зона, територія'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='repair',
            field=models.CharField(choices=[('authors_project', 'Авторський проект'), ('european_repair', 'Євроремонт'), ('cosmetical_repair', 'Косметичний ремонт'), ('life_condition', 'Житловий стан'), ('after_construction', 'Після будівельників'), ('for_clean_processing', 'під чистову обробку'), ('emergency_condition', 'Аварійний стан')], max_length=24, verbose_name='Ремонт'),
        ),
    ]
