# Generated by Django 2.2.7 on 2020-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_auto_20200224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
