# Generated by Django 2.2.7 on 2020-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20200102_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='district',
        ),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='notes',
            field=models.TextField(blank=True, help_text='<em>Бачите тільки Ви. До 1000 символів.</em>', max_length=1000, verbose_name='Примітки для службового користування'),
        ),
    ]
