# Generated by Django 2.2.7 on 2020-03-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20200226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='archivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Оголошення в архіві'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(help_text='до 70 знаків, повторно не редагується!', max_length=70, verbose_name='Заголовок'),
        ),
    ]
