# Generated by Django 2.2.7 on 2019-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0003_auto_20191125_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type_offer',
            field=models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда довгострокова')], default='sale', max_length=5, verbose_name='Тип оголошення'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('hrv', 'грн.'), ('dol', '$')], default='dol', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='floor',
            field=models.CharField(max_length=5, verbose_name='Поверх'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kitchen',
            field=models.CharField(max_length=5, verbose_name='Кухня площа'),
        ),
    ]
