# Generated by Django 2.2.7 on 2019-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20191125_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
