# Generated by Django 2.2.7 on 2020-01-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_auto_20200103_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sold_true',
        ),
    ]
