# Generated by Django 2.2.7 on 2020-01-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_auto_20200103_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн.'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
