# Generated by Django 2.2.7 on 2019-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='district',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн.'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта'),
        ),
    ]
