# Generated by Django 2.2.7 on 2020-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_auto_20200317_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='satellite_tv',
        ),
        migrations.AlterField(
            model_name='offer',
            name='cable_digital_tv',
            field=models.BooleanField(verbose_name='Кабельнеб або супутникове ТБ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн.'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
