# Generated by Django 2.2.7 on 2019-11-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0008_auto_20191128_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image9',
        ),
    ]
