# Generated by Django 2.2.7 on 2019-11-28 17:55

from django.db import migrations, models
import flats.models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0009_auto_20191128_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='contract',
        ),
        migrations.AddField(
            model_name='offer',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='offer',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 9'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=flats.models.Offer.user_directory_path, verbose_name='Фото 6'),
        ),
    ]
