# Generated by Django 2.2.7 on 2019-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0010_auto_20191128_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bathroom',
            field=models.CharField(choices=[('different', 'Роздільний'), ('adjacent', 'Суміжний'), ('two_and_more', '2 і більше'), ('no_bathrooms', 'Санвузол відсутній')], max_length=14, verbose_name='Санвузол'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='building',
            field=models.CharField(choices=[('royal', 'Царський будинок'), ('stalin', 'Сталінка'), ('hruschov', 'Хрущовка'), ('czech', 'Чешка'), ('guest', 'Гостинка'), ('sovmin', 'Совмін'), ('hostel', 'Гуртожиток'), ('90', 'Житловий фонд 80-90'), ('2000', 'Житловий фонд 91-2000'), ('2010', 'Житловий фонд 2001-2010'), ('2019', 'Житловий фонд від 2011'), ('constraction', 'На етапі будівництва')], max_length=12, verbose_name='Тип будинку'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн.'), ('USD', 'USD')], default='USD', help_text='Виберіть валюту', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Примітки для службового користування'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='planning',
            field=models.CharField(choices=[('adjacent', 'Суміжна, прохідна'), ('different', 'Роздільна'), ('studio', 'Студія'), ('penthouse', 'Пентхаус'), ('multilevel', 'Багаторівнева'), ('small_family', 'Малосімейка, гостинка'), ('smart_flat', 'Смарт-квартира'), ('free_planning', 'Вільне планування'), ('two_sides', 'Двостороння')], max_length=14, verbose_name='Планування квартири'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='walls',
            field=models.CharField(choices=[('brick', 'Цегляний'), ('panel', 'Панельний'), ('monolit', 'Монолітний'), ('wood', "Дерев'яний'"), ('cinder_block', 'Шлакоблочний'), ('air_concrete', 'Газоблок'), ('sip', 'СІП панель'), ('other', 'Інше')], max_length=10, verbose_name='Матеріал стін'),
        ),
    ]
